module AdventOfCode.Y2021.Day8 where

import AdventOfCode.Common.List (count)
import Data.List (sort)

--------------------------------------------------------------------------------

zero = "abcefg"   -- 6
one = "cf"        -- 2 UNIQUE
two = "acdeg"     -- 5
three = "acdfg"   -- 5
four = "bcdf"     -- 4 UNIQUE
five = "abdfg"    -- 5
six = "abdefg"    -- 6
seven = "acf"     -- 3 UNIQUE
eight = "abcdefg" -- 7 UNIQUE
nine = "abcdfg"   -- 6

digitSettings :: [String]
digitSettings = [zero, one, two, three, four, five, six, seven, eight, nine]

data SignalPattern = SignalPattern
   { input :: [String]
   , output :: [String]
   } deriving (Eq, Show)

--------------------------------------------------------------------------------

part1 :: [SignalPattern] -> Int
part1 = count ((`elem` [2,4,3,7]) . length) . foldMap output

--------------------------------------------------------------------------------

sampleInput :: [SignalPattern]
sampleInput = 
   [ SignalPattern ["be", "cfbegad", "cbdgef", "fgaecd", "cgeb", "fdcge", "agebfd", "fecdb", "fabcd", "edb"] ["fdgacbe", "cefdb", "cefbgd", "gcbe"]
   , SignalPattern ["edbfga", "begcd", "cbg", "gc", "gcadebf", "fbgde", "acbgfd", "abcde", "gfcbed", "gfec"] ["fcgedb", "cgb", "dgebacf", "gc"]
   , SignalPattern ["fgaebd", "cg", "bdaec", "gdafb", "agbcfd", "gdcbef", "bgcad", "gfac", "gcb", "cdgabef"] ["cg", "cg", "fdcagb", "cbg"]
   , SignalPattern ["fbegcd", "cbd", "adcefb", "dageb", "afcb", "bc", "aefdc", "ecdab", "fgdeca", "fcdbega"] ["efabcd", "cedba", "gadfec", "cb"]
   , SignalPattern ["aecbfdg", "fbg", "gf", "bafeg", "dbefa", "fcge", "gcbea", "fcaegb", "dgceab", "fcbdga"] ["gecf", "egdcabf", "bgf", "bfgea"]
   , SignalPattern ["fgeab", "ca", "afcebg", "bdacfeg", "cfaedg", "gcfdb", "baec", "bfadeg", "bafgc", "acf"] ["gebdcfa", "ecba", "ca", "fadegcb"]
   , SignalPattern ["dbcfg", "fgd", "bdegcaf", "fgec", "aegbdf", "ecdfab", "fbedc", "dacgb", "gdcebf", "gf"] ["cefg", "dcbef", "fcge", "gbcadfe"]
   , SignalPattern ["bdfegc", "cbegaf", "gecbf", "dfcage", "bdacg", "ed", "bedf", "ced", "adcbefg", "gebcd"] ["ed", "bcgafe", "cdgba", "cbgef"]
   , SignalPattern ["egadfb", "cdbfeg", "cegd", "fecab", "cgb", "gbdefca", "cg", "fgcdab", "egfdb", "bfceg"] ["gbdfcae", "bgc", "cg", "cgb"]
   , SignalPattern ["gcafb", "gcf", "dcaebfg", "ecagb", "gf", "abcdeg", "gaef", "cafbge", "fdbac", "fegbdc"] ["fgae", "cfgab", "fg", "bagce"] ]

myInput :: [SignalPattern]
myInput =
   [ SignalPattern ["dbcfeag", "cgaed", "fe", "bfgad", "aefcdb", "efa", "efgda", "gcef", "dcaebg", "dfeagc"] ["fae", "cfge", "fae", "baefdc"]
   , SignalPattern ["ea", "bfecadg", "bgafcd", "deac", "ebcag", "eab", "debfag", "eabgdc", "bcgfe", "bagdc"] ["cdbagf", "fagbcd", "bae", "fcegb"]
   , SignalPattern ["fbgdec", "cbgeaf", "cbfag", "bd", "bgda", "cgbfda", "dbf", "fecda", "bfadc", "cbedagf"] ["gecfdb", "cbfga", "bacgef", "dfb"]
   , SignalPattern ["geabdf", "cfbge", "dcbeaf", "aebdf", "dgea", "acdgfbe", "fag", "gfbea", "ag", "cabdfg"] ["dfeabc", "dbaefc", "fdaebc", "fga"]
   , SignalPattern ["gcae", "cefdg", "abdcgfe", "cg", "fcg", "afcegd", "dbgfea", "agdfe", "dcafbg", "bcdef"] ["gc", "caefdg", "gcf", "egdcf"]
   , SignalPattern ["efgcb", "fbac", "dbefg", "bce", "efacg", "fbgcdae", "cb", "egfbca", "dgfaec", "dcgbea"] ["fgecb", "bcfa", "bc", "efcag"]
   , SignalPattern ["efcgdb", "da", "bdefg", "dfegba", "fbacg", "gbcdea", "dbafceg", "adb", "feda", "fadgb"] ["da", "ad", "cgabde", "cebdga"]
   , SignalPattern ["ca", "fcabegd", "facd", "agbed", "acg", "cfadeg", "acdeg", "agcefb", "cdfgeb", "efcdg"] ["cdeafg", "cag", "efgadc", "gacbfe"]
   , SignalPattern ["fdacgb", "cfa", "cfage", "gabce", "dfagce", "edagfb", "dcbfeag", "fc", "fced", "gfdae"] ["gabdef", "fdegba", "gaedcf", "fac"]
   , SignalPattern ["acgdbf", "faedcbg", "fa", "cbgdae", "fgbdae", "aedbg", "adf", "fbea", "cfdge", "fedga"] ["fad", "egdcf", "feab", "bfcagd"]
   , SignalPattern ["ged", "cadgf", "gcdafeb", "cabgfd", "cgedf", "aedc", "ebfcg", "faebgd", "ed", "fcadeg"] ["dfgca", "gabefd", "dafgc", "ecfgd"]
   , SignalPattern ["bcedga", "dceba", "gcadfbe", "dfec", "adcbfe", "fda", "fabge", "df", "fbdae", "bcfgda"] ["adgcfbe", "fbgae", "dgebafc", "gacedb"]
   , SignalPattern ["fgcabde", "edbcfg", "efcdga", "dfbcea", "dbaeg", "fea", "fa", "dbaef", "acfb", "dbfec"] ["aecbfd", "aedcfb", "bdaef", "abfc"]
   , SignalPattern ["cfbd", "gefad", "dce", "fdeac", "dc", "ecabfd", "dgabce", "gabdecf", "afbce", "fagceb"] ["bdfc", "bcgaed", "bgdace", "afegd"]
   , SignalPattern ["acfgde", "egdfb", "dcaf", "gecfd", "ecdbgfa", "gcdbae", "cefgba", "dcg", "gcefa", "cd"] ["eadcbg", "cdfega", "fdgeac", "dgc"]
   , SignalPattern ["cadfgb", "edcgbfa", "dc", "cgd", "fegcb", "dfabg", "cdaebg", "dafc", "fcbdg", "gbdeaf"] ["afdc", "adcf", "befdag", "gfcdb"]
   , SignalPattern ["deafg", "ebafdcg", "gcdfba", "bge", "eb", "fgcbd", "gbefac", "bdce", "fdebg", "gdcfeb"] ["cbdagf", "bdce", "gdfeb", "fgead"]
   , SignalPattern ["acbdef", "bg", "agebdf", "afbcg", "fgbeca", "edafcgb", "eacfb", "gba", "ebgc", "fgcad"] ["begdaf", "gcbe", "ebdfag", "dabefg"]
   , SignalPattern ["ga", "agc", "bdegcaf", "gefbc", "cfdea", "dafgec", "fagce", "dgebca", "aefbdc", "gdfa"] ["acfedbg", "bfaecdg", "gca", "facedg"]
   , SignalPattern ["abdg", "ad", "egcabf", "ebagf", "afd", "gdfceab", "dcebf", "dagbef", "cdgafe", "deabf"] ["bfedc", "cbedf", "gdab", "afd"]
   , SignalPattern ["efbadc", "cafbd", "eba", "fegda", "fcbe", "dbefa", "efcbdag", "adbcge", "badfcg", "be"] ["be", "agdfe", "cedbag", "dcbeaf"]
   , SignalPattern ["adegb", "cgafb", "badgcfe", "fged", "fgaebd", "eabgf", "bceafd", "eaf", "eacbdg", "fe"] ["bdgeac", "adgbfe", "bdgae", "acfgbed"]
   , SignalPattern ["dbfega", "befag", "gbfdec", "gacfed", "fcgdabe", "bgf", "deagf", "bf", "dafb", "bceag"] ["bdfa", "cagbe", "gceba", "agbdfe"]
   , SignalPattern ["fecagd", "cbfeagd", "fdecb", "fg", "fgbde", "ebgda", "cagdbe", "fge", "gfab", "agefdb"] ["geabcd", "gdbea", "ebgafd", "egdab"]
   , SignalPattern ["ab", "agdcfe", "dcfgb", "cba", "adefcb", "adfbc", "bdae", "ebacgf", "aegbdcf", "fcade"] ["gfecda", "dfabc", "edab", "bfcad"]
   , SignalPattern ["bcfae", "ebd", "gefdacb", "fdceg", "dbaegc", "gdbf", "gcefbd", "cedfb", "adfgce", "bd"] ["gebdcf", "bd", "dgfb", "ebdcgf"]
   , SignalPattern ["gbcafde", "cdaef", "dfe", "ecbf", "egcda", "fadgcb", "bfdac", "dacfbe", "bgefda", "ef"] ["dcgafb", "dfaebg", "fbec", "agbdfc"]
   , SignalPattern ["fe", "cfedab", "dcfgeb", "gdbef", "gadeb", "cegf", "fgcbd", "fbe", "abdcgf", "ebacgfd"] ["debfg", "abecfd", "adbefc", "gdcbfe"]
   , SignalPattern ["ad", "cbfeda", "acegfb", "gdcaeb", "adcgfbe", "bda", "abefc", "dcabf", "fgcdb", "afde"] ["gdcbf", "cedbaf", "dbagec", "becfa"]
   , SignalPattern ["acegb", "efcgab", "edcfgab", "aebdc", "gce", "ge", "fage", "egcdfb", "agfbc", "cbdfga"] ["eg", "cafegb", "fcbeag", "acbgef"]
   , SignalPattern ["bcaf", "agefdc", "bcegaf", "eaf", "bdgfe", "agfdecb", "efgab", "af", "abegc", "dgacbe"] ["defbg", "dgaebc", "eaf", "cebga"]
   , SignalPattern ["edabcf", "bdeg", "gd", "cadebg", "dgcab", "gfcaed", "febdgca", "cdg", "beacd", "cagbf"] ["befadcg", "fbgca", "afdecg", "bgceda"]
   , SignalPattern ["gadfeb", "ag", "gfda", "cbeda", "fbeacg", "bgdcaef", "dgfeb", "eag", "gbdea", "fegcbd"] ["cabefg", "degbcf", "gdbef", "bcdgef"]
   , SignalPattern ["efbcda", "cgfd", "dgefac", "dfcgbae", "degaf", "adg", "debacg", "aedcf", "gd", "aebgf"] ["ecfad", "cgbade", "aegdcb", "gfbae"]
   , SignalPattern ["bdc", "cdfgb", "cabgf", "gabd", "fdebagc", "eabgcf", "bd", "abdcef", "gfcabd", "fgedc"] ["faecdb", "fgecd", "cbfdag", "bcfadg"]
   , SignalPattern ["dfagbec", "ceg", "egfad", "fdeabg", "acedg", "afedcg", "gc", "bcgaef", "eacdb", "fdcg"] ["gcfd", "eadbc", "dbegcfa", "eabcd"]
   , SignalPattern ["gfb", "egfba", "eadcfb", "gf", "adfg", "dgebfa", "dacfegb", "eagcb", "cbedgf", "fadeb"] ["edfba", "afgebd", "adbegf", "efcbda"]
   , SignalPattern ["fec", "caegd", "efgb", "cgaedfb", "gfbdec", "gfdbc", "ef", "cfdgab", "fdcge", "fbaedc"] ["abcdef", "gcfbd", "bfegdac", "gcead"]
   , SignalPattern ["gefdba", "abcef", "ead", "gedcab", "ad", "bfdecg", "cbged", "ebcad", "cafbdeg", "cadg"] ["defcgb", "ade", "bgecd", "ceabf"]
   , SignalPattern ["cabg", "adgefbc", "cb", "ebafg", "febgc", "fbc", "gdcfe", "cafedb", "egfabc", "aebdgf"] ["bcdafeg", "ecbafd", "adbecf", "fbcge"]
   , SignalPattern ["acged", "febgd", "agdcfb", "bdceg", "gdbecf", "bc", "bgc", "cfeb", "cfgbaed", "bgefad"] ["dceag", "efbc", "cbfdeg", "ebcdfg"]
   , SignalPattern ["gab", "adgcbef", "cebfg", "abdce", "dcbefg", "bafdgc", "abefgc", "aegf", "ag", "cgbea"] ["gaceb", "aegf", "fgcbe", "cgebf"]
   , SignalPattern ["fa", "baf", "cadfbge", "dbgef", "ebacgd", "dfceba", "adbec", "fdeba", "cfae", "dacgfb"] ["dabcef", "dafcbe", "acgdbe", "ecdfab"]
   , SignalPattern ["fgeca", "gecadfb", "aecdfb", "fb", "gcbed", "dfgb", "cgdbea", "ecfgb", "gfbdec", "efb"] ["abcedg", "bf", "bf", "agedcfb"]
   , SignalPattern ["fg", "aefgd", "bafcde", "gcfe", "bdgae", "gfa", "fedca", "cagdfb", "cfaedg", "ebgacfd"] ["dcfgab", "dgfea", "gf", "cafdgb"]
   , SignalPattern ["afbcge", "debgc", "cafdbg", "ae", "eadf", "afdgb", "gbdeaf", "aeb", "cgfebad", "abgde"] ["deaf", "cbafge", "cbegd", "aedbg"]
   , SignalPattern ["fbc", "afcegb", "fadgc", "fbeda", "cbed", "ecdafb", "cfdab", "cb", "fegdcab", "bdaefg"] ["cgfad", "ecbd", "edafb", "cgafd"]
   , SignalPattern ["fegbcd", "abcf", "gfabedc", "bgcad", "gfacd", "gedab", "efdagc", "dfgcab", "cdb", "bc"] ["fbca", "cdbag", "cdfgab", "cgedbfa"]
   , SignalPattern ["gfca", "gbdef", "eadcfg", "ebdcag", "dcg", "afecd", "gc", "decafbg", "fcegd", "bcfade"] ["gcefd", "bcdafge", "cdefg", "edfgc"]
   , SignalPattern ["gdae", "ad", "gecfd", "dcfaeb", "dfegcb", "gdcaf", "fdacge", "adf", "agbcf", "cebfgad"] ["dgebafc", "edfgc", "da", "cbgafed"]
   , SignalPattern ["ceg", "febgdca", "bfgdea", "gc", "adcfge", "cefbag", "agdc", "edfcb", "dfgce", "gadef"] ["ceg", "ebdagf", "agdfe", "afbgce"]
   , SignalPattern ["dabegcf", "bcdfag", "gdecb", "gdbeca", "gaebd", "fbdce", "bdagef", "cg", "bgc", "ecag"] ["dfcabg", "abfdge", "gadbe", "cg"]
   , SignalPattern ["dacefb", "efc", "gfaebc", "gbfe", "egcda", "agfbdc", "beadfcg", "fe", "fbcga", "cgafe"] ["ef", "fbaedc", "ef", "efc"]
   , SignalPattern ["cbgae", "faedbg", "fegab", "agc", "ebdgc", "eacf", "bgeafc", "ca", "cgdbafe", "gadcbf"] ["eagfb", "aebgf", "gcbfad", "gfeba"]
   , SignalPattern ["dcf", "dacbg", "bdcaef", "dfeacg", "gacfe", "cdfag", "fgde", "faecgb", "daebcgf", "df"] ["fcd", "fecadb", "egacf", "deabcf"]
   , SignalPattern ["egdfa", "dfaec", "gdab", "ga", "agf", "dbefga", "dgebf", "afbgecd", "bgafec", "bgefcd"] ["fegbd", "gdfbe", "begdfc", "efcbadg"]
   , SignalPattern ["cfd", "edafbc", "afbd", "cadbeg", "fgecbad", "gcaef", "dacef", "df", "dbcae", "efcdgb"] ["adbf", "cabde", "baegdc", "cgbeda"]
   , SignalPattern ["cbag", "gc", "cdgbe", "defbg", "agebdfc", "becda", "dbgcae", "cdg", "efacbd", "fecgad"] ["fcegabd", "abgc", "dacbe", "cdaebg"]
   , SignalPattern ["bf", "dacgf", "dfb", "befc", "fbedcg", "gebdc", "dbacefg", "abdegf", "gcdfb", "bedacg"] ["bfec", "feagcbd", "egdcb", "daegbf"]
   , SignalPattern ["aebgfdc", "gadcf", "gcdfeb", "dagce", "agdeb", "acfe", "bgacdf", "dec", "gfecad", "ec"] ["ceadg", "edcag", "fdcga", "cdbagef"]
   , SignalPattern ["befdgca", "dgcbf", "fedagc", "be", "bfe", "dcefb", "ecfdba", "acfed", "ebca", "ebgfda"] ["dfbcae", "bafgdce", "bgcdf", "egbdfa"]
   , SignalPattern ["bfa", "bdagfc", "dbega", "bfgea", "eagfdb", "dbgace", "bcefg", "dcbgeaf", "fa", "defa"] ["ebcgdaf", "aecgdbf", "fgcadb", "fa"]
   , SignalPattern ["agcdeb", "cgf", "agbdcef", "bgdfe", "efac", "cgefb", "abefgc", "cagdbf", "fc", "gebca"] ["fegbc", "acfe", "becga", "deagbc"]
   , SignalPattern ["adbfce", "agebd", "eadcbfg", "ega", "abedf", "fgab", "dgebc", "dgfcea", "ag", "agdebf"] ["gdfcabe", "ebadf", "ga", "bfag"]
   , SignalPattern ["gcebfd", "feacdbg", "acegfb", "afgce", "gbac", "geb", "cdaefg", "daefb", "gb", "fgbae"] ["agefb", "gb", "adfbe", "efabd"]
   , SignalPattern ["gadbfc", "ebgad", "dgecba", "fgae", "eacgdbf", "af", "ebcfd", "afd", "bdeaf", "gadefb"] ["fa", "bdgaef", "gdbacf", "af"]
   , SignalPattern ["bfeacd", "edgcabf", "dg", "gcabd", "cdaeb", "acfgb", "bcgdae", "dgae", "cgd", "bgfdec"] ["bedac", "acbed", "abcdfge", "dgc"]
   , SignalPattern ["cdage", "dgabec", "cbadg", "ge", "acfde", "edg", "becfagd", "gbec", "adbcgf", "fbeadg"] ["cdbgea", "cgdaeb", "cegad", "gdeac"]
   , SignalPattern ["ab", "gbaf", "cdegba", "fceadbg", "gfbecd", "bca", "eadcf", "fgeabc", "becfa", "cebfg"] ["cagfeb", "cefabg", "fcbeg", "eadcgb"]
   , SignalPattern ["afdec", "bcaefg", "ca", "abcd", "efcdg", "aec", "aebdf", "cdafbe", "begdaf", "eadgbfc"] ["cdfeg", "afdce", "edfac", "gdfabe"]
   , SignalPattern ["faebd", "fed", "df", "bgdcaef", "cbdega", "gdbeaf", "fbecgd", "badge", "afebc", "fadg"] ["dcebfg", "dgaf", "fd", "cdegfba"]
   , SignalPattern ["abdgf", "efg", "fe", "gdeabf", "cdbge", "cfadeg", "gdbef", "cafgdeb", "fbea", "bgcadf"] ["bgdfe", "fabe", "gbfadc", "gbfcda"]
   , SignalPattern ["agdfe", "cfbd", "dgfca", "cd", "abgfc", "cdgbea", "gbecfa", "gbadcef", "cda", "dfgbac"] ["cegfba", "fbcd", "bfdc", "dca"]
   , SignalPattern ["acdb", "bdcega", "dbfcge", "aedfgb", "dec", "fcega", "dc", "adegc", "fgceabd", "gaedb"] ["badeg", "bdecgf", "cd", "cdageb"]
   , SignalPattern ["abe", "ab", "dbecfag", "adgec", "agbf", "eadbg", "cbeafd", "fbcegd", "gadbfe", "bfgde"] ["ebgfd", "efdgb", "gceadbf", "ba"]
   , SignalPattern ["dgfceba", "egbcaf", "fgc", "bfgdca", "cbgfe", "cg", "faebc", "agce", "gdfeb", "debcaf"] ["bedfac", "edbfg", "aegc", "eabcdgf"]
   , SignalPattern ["bdfac", "dcfeb", "dbcefa", "dbgcaef", "fbae", "egdcb", "fgaecd", "fec", "cdbafg", "ef"] ["bdfagc", "dcfabg", "gdbfeca", "eabf"]
   , SignalPattern ["gfca", "dbcaf", "bfcgd", "fcgdeab", "degcb", "abcedf", "cbagfd", "gfb", "fg", "fdgabe"] ["gcaf", "bfg", "fbg", "gf"]
   , SignalPattern ["efcagd", "dbag", "fgd", "defgacb", "aebfg", "dbgfe", "bdeafg", "edfbc", "gd", "fgecab"] ["fbeag", "ecgfabd", "degacf", "debgfac"]
   , SignalPattern ["efcbg", "bacfe", "gbdce", "fge", "acegbdf", "cgdf", "aebdfg", "dgbcae", "ebcdgf", "gf"] ["caefb", "cbfdage", "ecfgb", "bgedc"]
   , SignalPattern ["fgdeb", "dcbfg", "fgae", "fbeagd", "edbfa", "aegdbc", "egb", "gafecdb", "bfdeca", "eg"] ["dgbcea", "bdaef", "gfbde", "dfgbea"]
   , SignalPattern ["bdcaf", "gdafc", "cbf", "bdefa", "cb", "fgceda", "bdfagc", "fcbgde", "afcgedb", "cbga"] ["gbca", "fbdca", "cegfdb", "fcagd"]
   , SignalPattern ["cfebgd", "cedgfa", "dcfabge", "dbfgc", "dgeb", "ge", "fcegb", "gfe", "abfdcg", "fecab"] ["fge", "fabec", "gfbadec", "bfceg"]
   , SignalPattern ["aeb", "ab", "gebfd", "abcdef", "edcag", "cdegaf", "gaedbc", "bgfecda", "debag", "gbac"] ["beacgd", "bdfeg", "afgecd", "gedbf"]
   , SignalPattern ["ab", "gebfadc", "acfge", "edafbc", "abegc", "dcegab", "gbecfd", "gbda", "cab", "ebcdg"] ["dagb", "cegfa", "bca", "bac"]
   , SignalPattern ["gaedb", "ebcd", "fgcea", "cba", "dcgafb", "febadg", "egcab", "adcbge", "efgadcb", "cb"] ["dfcagb", "cbed", "bagce", "dbce"]
   , SignalPattern ["ca", "dgfceb", "bfeacd", "fcbgd", "bdgca", "cfag", "gaedb", "abc", "fcbagd", "fgecadb"] ["cgdfab", "cfag", "bac", "cbfegad"]
   , SignalPattern ["gade", "gafcb", "bfgecd", "bge", "ecbda", "gdcbea", "eg", "beacg", "fdaecb", "agfbecd"] ["dgae", "bgfca", "abegc", "cfdebg"]
   , SignalPattern ["eac", "cdbef", "ac", "gfdae", "dagc", "afcedgb", "dcfae", "dafcge", "dbfega", "caebfg"] ["gafceb", "dbeacgf", "cdga", "fbcde"]
   , SignalPattern ["dbagfc", "bgedca", "df", "afgec", "daf", "beagdfc", "aefcbd", "bedac", "acfed", "dbfe"] ["bedca", "cdaef", "baecfd", "befcad"]
   , SignalPattern ["fdacb", "baedc", "acedfb", "bacedg", "fd", "gfcab", "ecdf", "daf", "fedgba", "befgdac"] ["egabcd", "cedab", "eabdfg", "adf"]
   , SignalPattern ["efdgc", "dfecga", "adfbe", "ac", "cage", "adc", "gfbdec", "cagbfd", "efdabgc", "caefd"] ["efdab", "efdgcab", "ca", "cedfg"]
   , SignalPattern ["ca", "acgf", "cadbgfe", "egfcab", "gefab", "cea", "defbc", "fecab", "edbcga", "fbgdae"] ["cfeba", "efdcbag", "dacebg", "agefcdb"]
   , SignalPattern ["bcedfa", "agecd", "ebgf", "fcbdg", "fde", "cgfed", "acgbfd", "cagfdeb", "ef", "cgbdef"] ["fgeb", "bcfdg", "def", "ef"]
   , SignalPattern ["bfcdea", "ga", "fbdegac", "gecdf", "cfdab", "bcgadf", "facdg", "aegbcd", "gac", "afgb"] ["cbadfg", "facdb", "afbg", "dfecba"]
   , SignalPattern ["fdcae", "afeg", "fa", "bceda", "dfebcga", "afcgdb", "dgecf", "acf", "fgceda", "cbfdeg"] ["fa", "bdfcga", "fcbegd", "efacd"]
   , SignalPattern ["efgbcd", "cf", "bdgace", "fgbad", "dfc", "fceabd", "dbaegfc", "bdcgf", "becdg", "gfce"] ["bcedaf", "adbegc", "badgec", "bgcfd"]
   , SignalPattern ["efcba", "ebdfga", "fda", "gdefbc", "da", "facde", "dacg", "fgedc", "gfeabcd", "acdefg"] ["da", "bgafde", "cegfd", "edafgb"]
   , SignalPattern ["daegb", "cbge", "bgcaed", "afgced", "ge", "cdabe", "fdbcaeg", "fcbeda", "bgfda", "eag"] ["gae", "egcb", "egbc", "egdafcb"]
   , SignalPattern ["cefda", "fadg", "bfedac", "bedfacg", "dgecfa", "eag", "ga", "fegcb", "becagd", "gcefa"] ["dcfea", "eag", "cedfa", "bgfcaed"]
   , SignalPattern ["dcfe", "gbeafd", "df", "bdcaf", "ebfcag", "fcedagb", "cdbag", "dcfaeb", "eabcf", "fbd"] ["dfce", "geacbf", "cefd", "ebdacf"]
   , SignalPattern ["efgbc", "agbd", "gd", "eadgcf", "becdfa", "bdace", "dge", "debgc", "adecgb", "bfdgcae"] ["bgcfe", "bedcg", "abgd", "gdba"]
   , SignalPattern ["cdbf", "edbfgc", "feadg", "cd", "ced", "gaecdb", "degfc", "efcgb", "fcbgaed", "befcga"] ["cfabgde", "fgdcbe", "efacgb", "abgcef"]
   , SignalPattern ["ae", "caegfd", "eadgc", "fedgba", "fecgd", "gbacd", "efac", "aed", "afcbged", "cgdbef"] ["ae", "eacf", "abdegcf", "eda"]
   , SignalPattern ["fc", "afcge", "dbgecf", "adcgfe", "eafbg", "gdebacf", "eagcd", "gfc", "aecdgb", "afcd"] ["cfg", "dgeac", "afbge", "edgcba"]
   , SignalPattern ["aedcg", "gfd", "cafgebd", "fg", "eadbgc", "adfcb", "cefg", "gabefd", "dacfg", "efcgda"] ["dgeca", "afgedb", "cfdga", "aefgcd"]
   , SignalPattern ["bfgaed", "facedb", "fbec", "dbgca", "cagfbde", "egcfda", "efdac", "acbfd", "fbd", "fb"] ["efbc", "agcdb", "fagdbe", "bacdf"]
   , SignalPattern ["fac", "dcae", "fgbda", "fagbce", "bdfac", "cbdfe", "ca", "cadbfe", "aegcdfb", "cebdfg"] ["cdea", "cfbdeg", "ac", "afdcb"]
   , SignalPattern ["geabcfd", "gfcaeb", "gcbead", "eba", "facbg", "fdgcab", "ea", "bgafe", "fdgbe", "caef"] ["bagef", "cafgb", "afbeg", "cbgaf"]
   , SignalPattern ["gcfdeb", "ceg", "fabcge", "edbag", "fcabdg", "bcgaf", "ceaf", "ec", "agefbdc", "cbega"] ["bgafc", "baecgdf", "bcfged", "gbdfeac"]
   , SignalPattern ["cf", "adgef", "cfgbaed", "bfdc", "gfc", "egcdfb", "dcgaeb", "degbc", "fcedg", "ecagfb"] ["fdbc", "cgdbe", "gdabce", "gfdce"]
   , SignalPattern ["bc", "afgcb", "cfdga", "dfcb", "cbdgea", "bgc", "efcgdab", "cfedga", "beafg", "bagcfd"] ["bc", "bc", "cbfadg", "adcbge"]
   , SignalPattern ["egdfb", "fa", "agfbe", "eacf", "befagc", "fba", "fbedacg", "cadebg", "agcbe", "cfgbda"] ["bagfec", "bcdgaf", "cbfgad", "dgcbfa"]
   , SignalPattern ["acgbde", "acgdbef", "cba", "ca", "bcgfd", "cade", "egdafb", "aebgfc", "agbed", "adgcb"] ["fdgbc", "gbadef", "gfcdbae", "edfgab"]
   , SignalPattern ["egbac", "efacgd", "gfbd", "fbcdag", "fecbad", "dgc", "badcf", "gfcebda", "dbcag", "dg"] ["bacdg", "facbegd", "cgd", "dfcgae"]
   , SignalPattern ["adgcf", "fbgcda", "efcgda", "dcbea", "fedg", "cfebag", "fae", "ef", "acdef", "gecbfda"] ["fcagd", "gcadf", "gcefdba", "gefabc"]
   , SignalPattern ["fegdba", "ba", "cedgaf", "gbade", "bfad", "egfda", "gba", "cadbgef", "gbced", "fcaegb"] ["gedaf", "bdega", "abgde", "bafd"]
   , SignalPattern ["gbacef", "gdab", "defgc", "bagfdc", "dfb", "afgcb", "efdbac", "bd", "dfbcg", "befcgad"] ["cdgef", "bd", "gbfac", "ecbgfad"]
   , SignalPattern ["fgacd", "ef", "dagfce", "ecdfa", "fae", "adfbgc", "cegf", "febdga", "ceabd", "bgacedf"] ["abcgfed", "gfce", "fae", "efacgdb"]
   , SignalPattern ["fbgdc", "afedg", "gcbafd", "gfedbc", "cfdag", "acd", "fbdeacg", "acbfde", "cgab", "ac"] ["gdcbf", "cedfbg", "dacgf", "dcafg"]
   , SignalPattern ["becf", "feadb", "abfedc", "dfcageb", "gcbda", "bafedg", "aec", "daecfg", "acdbe", "ec"] ["abdef", "fdeacg", "ace", "ecbf"]
   , SignalPattern ["dc", "cbfegda", "bfeadg", "dbcg", "gabfd", "adc", "dbcfga", "bface", "fgcade", "fdabc"] ["dacbgf", "dc", "cdfba", "dc"]
   , SignalPattern ["bc", "bfgedc", "fbc", "adfbceg", "cegb", "degcf", "eabdf", "defcb", "cdfgae", "fcagbd"] ["bcefd", "gceb", "fcagde", "cbfgad"]
   , SignalPattern ["ge", "cabgd", "egca", "egd", "adgbecf", "bfdagc", "decbag", "agbde", "deafb", "ebdgfc"] ["cagdfb", "bgecda", "cgedba", "fabdcg"]
   , SignalPattern ["cg", "cfagbd", "gcedfa", "efdbc", "gcd", "gbefda", "fegad", "efdcg", "caegdbf", "agce"] ["fgced", "dgfacb", "befdagc", "cefgda"]
   , SignalPattern ["bfedgc", "bec", "ce", "fcaebd", "efabg", "gdec", "cgfdb", "aebdfcg", "bfgcda", "cgbfe"] ["agebf", "bgdcfe", "ec", "agcbdf"]
   , SignalPattern ["db", "dfcbge", "edgfca", "gabd", "dcb", "agfcd", "bafcd", "afbgcd", "ebafc", "edgfbca"] ["acfdg", "cbdfa", "afceb", "gbda"]
   , SignalPattern ["cadegbf", "egdfbc", "adc", "acbdg", "dgbcf", "adgfbc", "da", "cgfdae", "fbda", "ebcga"] ["dgacb", "bagdc", "fgcbd", "aegbc"]
   , SignalPattern ["geacf", "abc", "gfedba", "cbadfg", "dbcg", "gfdba", "cagfb", "cb", "bfdcae", "adfecbg"] ["cb", "eadfgb", "bcfag", "dgcb"]
   , SignalPattern ["abdfcge", "adbeg", "badcef", "egcf", "fg", "fgb", "fbdec", "gebfd", "abgfcd", "gfebdc"] ["cbeadgf", "cfdbag", "gfdbe", "gf"]
   , SignalPattern ["facdbe", "acgfbd", "dbc", "bd", "abgcd", "adceg", "bcegfa", "fdgb", "bfgca", "badcfeg"] ["ceafdb", "bfcag", "dcgba", "bgdf"]
   , SignalPattern ["gcda", "cadbe", "abcedf", "cabeg", "edbgcf", "begcda", "begaf", "cg", "acbdefg", "gbc"] ["dbace", "gdbeac", "dacfgbe", "abdce"]
   , SignalPattern ["cgf", "gf", "fadegbc", "afgcde", "abgced", "fecba", "ceagf", "dcagbf", "fgde", "cdaeg"] ["gdebacf", "gf", "gdfe", "cfega"]
   , SignalPattern ["abdef", "bc", "gecaf", "dbcgfae", "cbfg", "efcba", "bac", "acebfg", "degcba", "dcegfa"] ["bcfadeg", "afceb", "edfgac", "gcabed"]
   , SignalPattern ["bfcged", "bgdac", "becad", "fagc", "aegbdfc", "gacfdb", "dbgfc", "dafgbe", "ga", "bga"] ["fgdecab", "abdcg", "cefabdg", "egdbfa"]
   , SignalPattern ["abcfg", "baecf", "agec", "fcgaeb", "agedbf", "ag", "dacfbeg", "bag", "eafcdb", "fcgdb"] ["bcdfea", "efdabg", "ga", "fdbgc"]
   , SignalPattern ["ba", "baf", "dfbgce", "cgab", "cefgdab", "efcad", "efacbg", "cgfeb", "ebafgd", "cafeb"] ["fdcegb", "abf", "baf", "ecabf"]
   , SignalPattern ["cegafd", "egdcba", "gbedf", "cgfde", "cfad", "ecf", "fcegadb", "eagdc", "bgaefc", "cf"] ["bfged", "defgb", "gbfed", "efc"]
   , SignalPattern ["gedfa", "abdce", "fadbe", "ebfc", "fba", "badgce", "bf", "gabefcd", "fdbgac", "befcad"] ["bcdgaf", "fdbgca", "bfa", "fgbdca"]
   , SignalPattern ["bacef", "cg", "dgabec", "agfc", "edfgb", "cge", "agfdbec", "fcabeg", "cgebf", "abfdce"] ["decfbga", "cagf", "adcgbe", "dgefb"]
   , SignalPattern ["eafgd", "ce", "fbgaced", "ecfga", "eafdgc", "gdce", "cea", "cefdba", "cbfag", "bdgafe"] ["eadfbg", "dgec", "efgca", "degfa"]
   , SignalPattern ["decgabf", "fecd", "acd", "acbegf", "agdec", "gabed", "gacbfd", "faceg", "cd", "fgeadc"] ["dc", "dcafge", "abecgf", "dc"]
   , SignalPattern ["egd", "fdaebg", "gcbeadf", "fcdge", "ge", "adecf", "gbce", "dgfbac", "dcfgeb", "gdbcf"] ["fdcae", "gfdbea", "bdfcg", "eg"]
   , SignalPattern ["ad", "cbafe", "dabe", "dfa", "gbfcea", "ceafd", "dcbagf", "fabdce", "bfceadg", "dfgec"] ["cebaf", "aecbgdf", "cgdbfa", "fbaec"]
   , SignalPattern ["fc", "cdgbae", "gfcbad", "badcg", "fcdba", "feadb", "fac", "cgefad", "fdgbeac", "gfbc"] ["cf", "cfabd", "caf", "gdfcea"]
   , SignalPattern ["fdgace", "edac", "cdfag", "de", "dcfge", "facebgd", "cgebf", "dfebag", "def", "bafgdc"] ["fdgac", "gacfbed", "edgacf", "dgcfa"]
   , SignalPattern ["gedfac", "acedb", "fbcadge", "acgefb", "dbgf", "fdaeb", "dgafe", "fgaedb", "bf", "fba"] ["fb", "bf", "bf", "agefcd"]
   , SignalPattern ["gefbdca", "fagbed", "cgaeb", "gf", "ebdfa", "gdbf", "afebg", "feg", "feadcb", "geacfd"] ["egf", "fedab", "gaefb", "eagbf"]
   , SignalPattern ["efadgbc", "bfag", "edgcb", "cga", "cefab", "afbegc", "ga", "gaebc", "eafcdb", "daefgc"] ["ga", "acg", "gcfbade", "dgecb"]
   , SignalPattern ["efcgbd", "gebcf", "gcadbf", "agfce", "fcdeagb", "gfa", "ageb", "aefdc", "ga", "gacbef"] ["gcebaf", "geba", "acfde", "fga"]
   , SignalPattern ["ga", "adbg", "fdeac", "gfa", "fdgbcae", "dgfabc", "cfgdb", "fegbdc", "fcabge", "agcdf"] ["adbcfg", "efadc", "agcdf", "cgdbf"]
   , SignalPattern ["febdc", "dacfeb", "gbfce", "cfgae", "bge", "bgdf", "dgcfbea", "baecdg", "gb", "ecfgbd"] ["gb", "fcedb", "becdf", "gb"]
   , SignalPattern ["bgacfd", "cdfabeg", "adgce", "bcegd", "acdefg", "gb", "cgb", "bgae", "ecbadg", "bdfec"] ["adcbfg", "gdfcea", "deafbcg", "ceadfg"]
   , SignalPattern ["bc", "gdfeac", "fbaec", "egfcba", "dacbeg", "cab", "gacbfde", "eabfd", "faceg", "fgcb"] ["afbegc", "cdgabe", "bagecf", "ebcdga"]
   , SignalPattern ["fd", "dfe", "fdgae", "abegfd", "dbcaeg", "dfgb", "caedbf", "efcag", "dageb", "dbfeagc"] ["dgfb", "gaedbf", "gfbd", "dgfcabe"]
   , SignalPattern ["agefbc", "aefdb", "abdge", "cdef", "bfdcga", "dacbf", "fe", "gbdcefa", "eabcdf", "efb"] ["cdbefa", "adfcbg", "fecagdb", "ebf"]
   , SignalPattern ["gbade", "adecfg", "abegcdf", "dcbfa", "cgbafd", "cfeb", "dfaebc", "fe", "feabd", "efa"] ["dbcfea", "bcfe", "fecb", "bafde"]
   , SignalPattern ["dfba", "dfc", "efbac", "cgead", "ecfgab", "gdfecb", "edacbf", "df", "afced", "bgecfad"] ["afdce", "bcfegd", "efgbac", "adgce"]
   , SignalPattern ["abfcg", "egacf", "bceafg", "dabgc", "fgb", "fb", "fbecadg", "fbce", "gafcde", "gfdbea"] ["abdgc", "defagb", "cbef", "egcaf"]
   , SignalPattern ["caegb", "decgbfa", "cebf", "edacg", "cgfbae", "gbc", "gfbea", "baedgf", "bc", "bfcdag"] ["agebc", "bgcae", "cbg", "gefba"]
   , SignalPattern ["ad", "gadf", "feacg", "aed", "agbfce", "egcda", "fedcba", "abcdgef", "bcdge", "gecafd"] ["gedfca", "ad", "febgac", "dcaebf"]
   , SignalPattern ["cegbd", "bgcfda", "dbfeag", "acef", "gcead", "cagfde", "dcfga", "gae", "fagbced", "ae"] ["defgab", "dacgf", "cebdg", "gecdfa"]
   , SignalPattern ["fag", "edfcg", "cdfa", "fa", "ceagfd", "fdgabe", "gebac", "egbfcd", "egdcfab", "gcaef"] ["acebg", "fag", "fgdec", "dfegcb"]
   , SignalPattern ["abe", "bcdfa", "acdbgf", "befd", "eadbc", "acbfgde", "eb", "fgcaeb", "gacde", "fcdbea"] ["eadbc", "afdgbc", "bgaefc", "cabfdeg"]
   , SignalPattern ["afdgce", "dgabe", "dgfbe", "bdegfc", "dfg", "agcbdfe", "fd", "abegfc", "dcfb", "bfgce"] ["debag", "bedgf", "ebdcfg", "cgebafd"]
   , SignalPattern ["dgfcea", "eagcbd", "gfceb", "adgb", "cgdeb", "dg", "eacdbf", "bedcafg", "dge", "abedc"] ["ecbgf", "dg", "dbfcgea", "ebcad"]
   , SignalPattern ["dgecf", "badfce", "egcdfab", "efabd", "edfca", "ac", "badc", "gbcfae", "eagdfb", "caf"] ["feadc", "febad", "dacef", "caf"]
   , SignalPattern ["gfb", "bacgde", "acbdgf", "afbd", "bdgca", "bf", "bgfdcea", "ecfag", "dgfecb", "fbcag"] ["fbgdcae", "gdfbca", "fbg", "fgaec"]
   , SignalPattern ["bcdg", "dc", "gedabc", "dec", "cdeag", "cbedaf", "gfaebc", "dafge", "bcegdaf", "agceb"] ["dfage", "bcefad", "cfbage", "fdgae"]
   , SignalPattern ["gc", "cag", "agbec", "dacbe", "dcbg", "edcbgaf", "gdcfae", "dacebg", "eabfg", "febacd"] ["gc", "cbdg", "gc", "fedcba"]
   , SignalPattern ["gfdbace", "edbc", "ecfgab", "efcdbg", "ce", "fdcabg", "fedga", "egc", "cbdgf", "gedfc"] ["ecdb", "edgfbc", "eagcfb", "cdafbg"]
   , SignalPattern ["afceg", "bgdeaf", "daceg", "degacb", "fe", "dfec", "adfgec", "acdgefb", "gcbfa", "gfe"] ["efg", "gcfea", "dcfe", "fcgea"]
   , SignalPattern ["bdca", "gcfdbea", "dc", "acbedf", "gbfde", "cagefd", "cfebag", "dcf", "bdcfe", "ebafc"] ["eafbc", "bcfage", "defcb", "agcbfe"]
   , SignalPattern ["cabefg", "adgeb", "fd", "dacf", "afgcb", "bgefdca", "decbfg", "fbd", "dafgb", "dfagbc"] ["gbfca", "cbeagf", "cfbgad", "fbd"]
   , SignalPattern ["bacgef", "defcga", "afdgebc", "facebd", "afebc", "badc", "bdfeg", "dc", "dbfec", "dce"] ["adbc", "eafdcb", "dabc", "fgedb"]
   , SignalPattern ["cdf", "decb", "fagec", "dc", "dcgbaf", "bacfgde", "gdfeb", "efbadg", "efgbdc", "cfged"] ["ecgfa", "efgbd", "fedgab", "dc"]
   , SignalPattern ["faebgd", "egdfcb", "gecadb", "gdbce", "ag", "aeg", "cgeab", "gacd", "faecb", "debcafg"] ["ag", "fdeabg", "decbg", "ag"]
   , SignalPattern ["eagc", "bdegf", "ga", "gdaef", "adg", "cbgdaf", "cfaegd", "dabfce", "adcegbf", "dfeac"] ["acedfg", "agd", "cega", "bgefd"]
   , SignalPattern ["cfgbe", "ceadf", "ab", "cbefag", "cegfbd", "bega", "egdfcab", "fba", "gbfacd", "efcba"] ["ceafbg", "abf", "ecfba", "ba"]
   , SignalPattern ["fgdce", "ecgbaf", "gebd", "bfg", "fdbac", "dfacge", "fbegdc", "cgbdf", "dacbfeg", "gb"] ["aebcgfd", "cdabf", "ebdg", "egdcaf"]
   , SignalPattern ["febda", "edagf", "egf", "gdcf", "bcgafed", "fg", "agcbfe", "caged", "gcadeb", "dgaefc"] ["cegbad", "gcdf", "gaedc", "ebdgca"]
   , SignalPattern ["eabgf", "fbdcg", "dfecag", "acebgf", "bafdge", "fbgce", "ecf", "eacb", "begfacd", "ec"] ["fbgea", "gcefb", "fegcad", "decfag"]
   , SignalPattern ["fabgcd", "febdac", "acgdf", "beagc", "dgaec", "de", "eafcdg", "dcfbeag", "dae", "fdge"] ["fcdgea", "ceadg", "fegd", "bdcaef"]
   , SignalPattern ["bcafeg", "ecbad", "dcfe", "ecbgafd", "gdefab", "dfabce", "de", "cadgb", "ebd", "fcaeb"] ["bed", "bgeafd", "fgeacb", "ecdfba"]
   , SignalPattern ["afcgeb", "gcebf", "cdbfag", "cfea", "bdgfe", "cbgaf", "ec", "gfabecd", "bedgca", "egc"] ["gce", "dacfbg", "cebfg", "afec"]
   , SignalPattern ["ecdafb", "cfeag", "bdgaf", "febga", "egabfc", "eb", "gbec", "fcebdga", "eab", "dfegac"] ["bea", "gbafd", "eab", "befdac"]
   , SignalPattern ["fgbacd", "fbcedga", "fgc", "fg", "gdaf", "bcdgef", "cdfba", "fabced", "cgbfa", "gcabe"] ["egcadfb", "adgf", "gbcefd", "gcf"]
   , SignalPattern ["dfbcga", "caefbd", "ac", "gaedbfc", "afgc", "afgdb", "bdgce", "dgcab", "fdgaeb", "dca"] ["afbgd", "cagf", "adc", "bfedga"]
   , SignalPattern ["bdgce", "dbf", "cgeadfb", "fd", "gfbde", "dfbecg", "gaebf", "dacgfb", "cdebga", "dcef"] ["fegbd", "fgbde", "bgfde", "fcegbd"]
   , SignalPattern ["gbda", "egadbf", "bfegd", "acgfde", "bfgaec", "gabef", "cfbde", "aefdbcg", "dg", "ged"] ["abgefd", "gdefba", "deg", "gfeba"]
   , SignalPattern ["afebcd", "degcfb", "dce", "dcfgb", "degf", "bdcgafe", "bdcge", "gcabdf", "de", "cbaeg"] ["de", "bagec", "gcdeb", "ebagc"]
   , SignalPattern ["eadcfg", "dfc", "gcbfade", "cd", "edafb", "fbcge", "afdbec", "agdbef", "ecfbd", "bdac"] ["efdab", "agefdc", "befad", "defabc"]
   , SignalPattern ["agbedf", "degbfc", "begcd", "ceagdf", "cgabe", "ecd", "dcbf", "ebfdg", "abecgfd", "cd"] ["fdebg", "fdgbe", "cdgeb", "bagdef"]
   , SignalPattern ["aefdb", "degf", "fdbaeg", "egb", "agebd", "bcfage", "gcedfab", "bdagc", "ge", "febacd"] ["bgfdae", "fdge", "acfdeb", "deafb"]
   , SignalPattern ["cegfba", "dfcea", "gbea", "bac", "ebafc", "gdcebf", "gebcf", "ba", "gfdbac", "gacfdbe"] ["febac", "aefcb", "cbfgda", "cafed"]
   , SignalPattern ["ec", "ecfab", "feadbg", "ecb", "dabfc", "cbfegd", "dbafgec", "feabg", "caefgb", "ecag"] ["acbefg", "afbeg", "fecgabd", "bcfad"]
   , SignalPattern ["fd", "decag", "fagbe", "beafdg", "egdacbf", "gbfcde", "dbfa", "agfbec", "dgf", "geadf"] ["bfda", "befgcda", "fgd", "adfb"]
   , SignalPattern ["af", "eabfdg", "edabc", "dgfabc", "efga", "fdbae", "fcagbed", "abf", "gbcdfe", "efgdb"] ["gefa", "gfabcd", "fba", "gcdfab"]
   , SignalPattern ["dbfacg", "degcb", "gecdaf", "adcbg", "bafegcd", "dfbag", "gbdefa", "ac", "cabf", "agc"] ["bcadg", "afbc", "bdgfa", "abcdg"]
   , SignalPattern ["efab", "cbedg", "aedfbc", "bfcad", "geacfd", "ea", "fabdcg", "adbfgce", "ade", "ecabd"] ["fdceba", "bfceda", "ecgdfa", "aefcdg"] ]
